### PR TITLE
requirements.sh

### PR DESCRIPTION
**Pull request by midu16**
Hello @hhorai ,

```requirements.sh``` is design to install the golang designated version used also on the ```free5G project```.  The scope will be to run the script as a pre-requirement installation of the environment and set all the package dependencies.

Thank you,
M

### CODE REVIEW

**Comment by hhorai** [comment]
Hi, @midu16 

Thank you very much for your contribution.
I have reviewed your code. That is helpful for people who test with free5gc.
I would like to suggest to you a bit change.
If you don't mind, could you rename `requirements.sh` to `tools/setup.sh`.

Because I think
    - `requirements.sh` is the requirement for free5gc, but not for gnbsim.
    -  gnbsim should be work with the latest version of golang.
    -  gnbsim can be run on arm environment which is not amd64.

**Comment by midu16** [comment]
Hey @hhorai ,

Thank you for your valuble insignts. 
I will include your suggestions and also add the ```arm``` environments compatibility. 
So the minimum requirement of golang version is the one used in the ```free5g```project? I deployed ```gnbsim```on my sistem, but because was not super obvious in the ```README.md``` i used the ```free5g``` version. 

My intention is to add more features to this project, if is ok with you.

Thanks,
M

**Comment by hhorai** [comment]
`the minimum requirement of golang version is the one used in the free5g project?`

My test env is
```
horai@raspi:$ go version
go version go1.13.15 linux/arm
```

And the following versions are working correctly that is reported by gnbsim user
```
1.14.4
1.15.2
```

When you install the latest golang in your test env, it should be worked well.
If it doesn't work, I will fix it.

**Comment by midu16** [comment]
Hey @hhorai ,

pushed the latest changes. Has been tested sucessfully on ```armv7l``` , ```armv8```, ```armv6l``` and ```x86_64```.

Thanks,
M

**Comment by hhorai** [comment]
Thank you for responding to my suggestion. The filename looks good to me.
But at this moment, It seems that you added changes for editor settings.
I use vim too. But other people might not use vim.
My next proposal is to remove vim related code block (line:10 - line:29).

**Comment by midu16** [comment]
Hey @hhorai ,

I removed the vimrc config. I will only keep for myself.

Thank you,
M

**Pull request merged**
